baseURL = "https://bugs.ada-risques.fr/"
languageCode = "fr-fr"
title = "Bug tracker Ada Risques"
disableKinds = ["taxonomy", "taxonomyTerm"]

[Params]
issuesApi = "https://api.github.com/repos/adarisques/bugs/issues"
